import type { Track } from "../types";

export const dataTrack: Track = {
  slug: "data",
  title: "Data you can trust",
  blurb:
    "The schema outlives every screen built on top of it. This is the layer where a bad decision is still costing you in two years, and the layer where generated code is weakest — a model will happily hand you a table that works today and is unfixable by March.",
  topics: [
    {
      slug: "data-modeling",
      title: "Model the thing, not the screen",
      hook: "The most expensive mistakes get made in the first twenty minutes of a schema.",
      minutes: 7,
      idea: [
        "A schema is a claim about what exists in the world, independent of any UI. The junior instinct is to model the form: the screen has five fields, so the table gets five columns. The senior instinct is to ask what the **nouns** are, how many of each relates to how many of the other, and what is true about each one regardless of which screen is open.",
        "",
        "Start from normalization: **every fact lives in exactly one place**. If a fact is written in two columns, the two will disagree — not might, will. Denormalizing is a legitimate move, but it is a later, deliberate one, made for a measured reason, and it carries the obligation to keep the copies in step.",
        "",
        "Four tells that you are modelling the screen:",
        "",
        "- A comma-separated list in a text column. That is a one-to-many you have not admitted to yet.",
        "- A column that is only meaningful when another column has a particular value. That is two entities wearing one trenchcoat.",
        "- Columns named `extra_1`, `extra_2`. That is a child table.",
        "- A nullable column where null means something. \"Not applicable\", \"not filled in yet\" and \"deliberately blank\" are three different facts sharing one representation.",
        "",
        "The other half of the job is **keys**. A primary key should be meaningless and immutable — which is why a UUID or a generated integer beats an email address, because people change those. And know what a foreign key buys: the database refusing to hold an order for a customer who does not exist, forever, no matter what code anyone writes later.",
      ].join("\n"),
      bites: [
        "It bites on the second feature, never the first. \"Also let me add a second reviewer\" is a five-minute change if reviewers are a table, and a three-day migration with a backfill and a deploy window if `reviewer_email` is a column on the sprint. The cost is not the typing; it is that the data already in production has to be transformed without losing any of it, while the app is running.",
        "",
        "It bites again in reporting. Every question you cannot answer with a query — \"how many tasks came from notes?\" — is usually a modelling decision from a year ago, not a missing feature.",
      ].join("\n"),
      decisions: [
        "One table or two? Ask whether the thing has its own lifecycle, its own identity and its own rules. If yes, it is its own table.",
        "Nullable column or separate table? If null would mean \"not applicable\" rather than \"not yet known\", you probably want a second table.",
        "Enum, check constraint, or lookup table? Enums are fast and rigid; lookup tables let non-engineers add values. Decide on who owns the list.",
        "Store the derived value or compute it? Store it only when computing is measurably too slow — and then own the job of keeping it correct.",
        "Soft delete or hard delete? Soft delete is a schema-wide tax: every query from then on must remember the filter. Only take it if you genuinely need the history.",
      ],
      inYourCode: [
        "Open your own migrations folder and pick a nullable column. Say out loud what null means there. If it means more than one thing, you have found a modelling bug.",
        "Find a foreign key with `on delete cascade`. Trace what would actually disappear if the parent row went. Is that what you want?",
        "Pick any table and state the cardinality of every relationship it is in, from memory, before you look. Then look.",
      ],
      gotIt: [
        "You notice a new field being added to the wrong table before it ships.",
        "You can explain why a given column is nullable, and what null means there, without hedging.",
        "Reaching for a child table stops feeling like extra work.",
      ],
      deeper: [
        { label: "Database Design for Mere Mortals — Hernandez, chapters 1–7" },
        {
          label: "PostgreSQL docs: Data Types",
          url: "https://www.postgresql.org/docs/current/datatype.html",
        },
      ],
    },
    {
      slug: "constraints",
      title: "Constraints are the cheapest tests you will ever write",
      hook: "A rule in the database holds against every future code path, including ones written by someone who never read your validation.",
      minutes: 5,
      idea: [
        "Application validation protects the path you thought of. A database constraint protects **every** path — the admin script, the manual fix at 2am, the second service someone adds next year, the generated endpoint that skipped your Zod schema.",
        "",
        "The tools, roughly in order of how badly they are under-used:",
        "",
        "- **NOT NULL** — the default should be `not null`, and nullable should be the thing you argue for. Most nullable columns are nullable because nobody decided.",
        "- **CHECK** — `char_length(title) between 1 and 200`, `amount > 0`, `ends_at > starts_at`. Each one is a bug that can never happen again.",
        "- **UNIQUE**, including composite. `unique (owner_id, dedupe_key)` is the difference between an idempotent operation and a duplicate-charge incident.",
        "- **FOREIGN KEY**, with a deliberate `on delete` action rather than whatever got typed first.",
        "- **DEFAULT**, so that adding a column does not silently make every old row meaningless.",
        "",
        "The mental model: **the schema is the last line of defence, and it never gets tired.** Validation in the app exists to produce a good error message. Validation in the database exists to be right.",
        "",
        "One real limit: constraints are cheap to add to an empty table and expensive on a large one, because the database must verify every existing row. Add them early. Adding them later means first finding and fixing the rows that already violate them — and there will be some.",
      ].join("\n"),
      bites: [
        "It bites as data corruption, which is the worst class of bug because it is silent and cumulative. By the time anyone notices that some rows have a blank title, or that two rows share a key that was supposed to be unique, you cannot tell which ones are wrong. The fix is a spreadsheet and a judgment call, not a deploy.",
        "",
        "It bites again as defensive code. A codebase littered with `if (!row.title) return` is usually a codebase with a missing NOT NULL.",
      ].join("\n"),
      decisions: [
        "Where does this rule belong — form validation, server validation, or the schema? Usually all three, for different reasons.",
        "Is this constraint cheap now and expensive later? Almost always yes. Add it now.",
        "What should `on delete` do — cascade, restrict, or set null? Each is a product decision, not a technical default.",
        "Should the uniqueness be partial? `unique (owner_id, slug) where deleted_at is null` is often what you actually meant.",
      ],
      inYourCode: [
        "Count the nullable columns in one of your tables. For each, decide whether null is a real state or an unmade decision.",
        "Find a place where the app checks something the database could enforce, and add the constraint.",
        "Look at your XP table's dedupe key. Notice that the unique constraint — not the code — is what makes double-awards impossible.",
      ],
      gotIt: [
        "Writing a migration, your first question is \"what must always be true here?\", before \"what columns do I need?\".",
        "You can name what would go wrong if a specific constraint were dropped.",
      ],
      deeper: [
        {
          label: "PostgreSQL docs: Constraints",
          url: "https://www.postgresql.org/docs/current/ddl-constraints.html",
        },
      ],
    },
    {
      slug: "indexes",
      title: "Indexes, and why your query got slow",
      hook: "Everything is fast on a hundred rows. The question is what happens at two million.",
      minutes: 8,
      idea: [
        "An index is a sorted copy of some of your columns, kept up to date on every write, that lets the database find rows without reading the whole table. That sentence contains the entire trade-off: **reads get faster, writes get slower, disk gets used**.",
        "",
        "**A sequential scan is not always bad.** On a small table it beats an index. The database decides, using statistics about your data — which is why \"slow in production, fast locally\" is such a common surprise. Different data, different plan.",
        "",
        "**Column order in a composite index matters enormously.** An index on `(owner_id, created_at)` serves a query filtering on `owner_id` alone, and one filtering on both. It does not serve a query filtering on `created_at` alone. Rule of thumb: equality columns first, then the range or sort column.",
        "",
        "**The index must match the query's shape.** Filter on `lower(email)` while indexing `email` and the index goes unused. If every query carries `where deleted_at is null`, a **partial index** with that same condition is smaller and faster.",
        "",
        "**`EXPLAIN ANALYZE` is the whole skill.** Not reading about indexes — running the query and reading the plan. Learn to spot three things: a `Seq Scan` on a big table, a row-count estimate wildly different from the actual, and a nested loop running thousands of times.",
        "",
        "The senior habit is not \"add indexes\". It is: **before writing a query, know which index will serve it** — and if none will, decide whether to add one or change the query.",
      ].join("\n"),
      bites: [
        "It bites at the worst possible moment: after launch, under real data, usually on the page users care most about. And it bites asymmetrically. A missing index on a 2M-row table does not make a page 20% slower; it makes it time out.",
        "",
        "The opposite bites too. A table with eleven indexes, because every slow query got one added, now writes eleven times on every insert, and the nightly import takes four hours.",
      ].join("\n"),
      decisions: [
        "Add an index, or change the query? Sometimes the query is asking for something it does not need.",
        "Which column goes first in the composite index? Equality before range, almost always.",
        "Partial index or full? If every query carries the same `where`, make it partial.",
        "Is this table write-heavy? Then every index has a real cost and has to earn its place.",
      ],
      inYourCode: [
        "Take your slowest page's query and run `EXPLAIN ANALYZE` against production-sized data. Read the plan top to bottom.",
        "Look at the indexes you have already declared. For each, name the query it serves. If you cannot, it may be dead weight.",
        "Find a query filtering on a column with no index, and picture that table at 2M rows.",
      ],
      gotIt: [
        "You can read an EXPLAIN plan and say where the time went.",
        "You notice a missing index while writing the query, not after the incident.",
        "You can explain why adding an index made writes slower.",
      ],
      deeper: [
        {
          label: "Use The Index, Luke — the best free resource on this",
          url: "https://use-the-index-luke.com/",
        },
        {
          label: "PostgreSQL docs: Using EXPLAIN",
          url: "https://www.postgresql.org/docs/current/using-explain.html",
        },
      ],
    },
    {
      slug: "transactions",
      title: "The write that half-happened",
      hook: "Two writes that must both land, or neither. Most code assumes this; very little code arranges it.",
      minutes: 7,
      idea: [
        "A transaction is a promise: everything inside it happens, or none of it does, and nobody else sees the middle. The acronym is **ACID**, but the two letters that matter daily are **atomicity** (all or nothing) and **isolation** (concurrent transactions do not see each other's half-finished work).",
        "",
        "The everyday shape of the problem: you insert a row in table A, then update a row in table B. Between those two statements anything can happen — the process is killed, the connection drops, an exception is thrown three lines down. Without a transaction you are left with A done and B not, and no code path that will ever fix it.",
        "",
        "**Isolation levels** are the part people skip. At Postgres's default, `READ COMMITTED`, each *statement* sees a fresh snapshot. So reading a row, deciding based on it, and then writing is **not** safe: the row can change in between. That pattern is read-modify-write, and it is behind most real-world data races. The fixes are to do it in one statement (`update ... set count = count + 1`), take a lock (`select ... for update`), or raise the isolation level and be ready to retry.",
        "",
        "**Keep transactions short.** A transaction holds locks. A transaction that calls an external HTTP API while holding a row lock is a production incident with a scheduled start time.",
        "",
        "And know the boundary: a transaction cannot roll back an email you already sent or a payment you already charged. Anything outside the database is outside the promise.",
      ].join("\n"),
      bites: [
        "It bites as data that makes no sense with no bug to explain it: an order with no line items, XP awarded twice, an invite marked used with no membership created. There is no stack trace, because nothing crashed *here* — the crash was somewhere else, halfway through.",
        "",
        "It bites hardest in generated code, which reliably produces a sequence of separate awaits where a transaction was needed, because each statement looks correct on its own.",
      ].join("\n"),
      decisions: [
        "Do these writes have to be atomic? If a half-done state is nonsense, yes.",
        "Is there a read-modify-write here? Make it one statement, or lock, or accept and handle a retry.",
        "Does anything slow or external belong inside this transaction? Move it out.",
        "If this must touch both the database and an external service, which goes first — and what cleans up if the second fails?",
      ],
      inYourCode: [
        "Find a server action that writes to two tables. Ask what state you are left in if the process dies between them.",
        "Find a place that reads a count, adds one, and writes it back. That is a lost update waiting for a double-click.",
        "Look at how your XP award avoids double-counting: it leans on a unique constraint rather than a transaction. Work out why that is sufficient here.",
      ],
      gotIt: [
        "\"What if this dies right here?\" is a question you ask while writing, not while debugging.",
        "You can explain why read-modify-write is unsafe at READ COMMITTED.",
      ],
      deeper: [
        { label: "Designing Data-Intensive Applications — Kleppmann, chapter 7" },
        {
          label: "PostgreSQL docs: Transaction Isolation",
          url: "https://www.postgresql.org/docs/current/transaction-iso.html",
        },
      ],
    },
  ],
};
