import type { Track } from "../types";

export const failureTrack: Track = {
  slug: "failure",
  title: "Everything breaks",
  blurb:
    "The single clearest difference between one year of experience and five is how vividly you picture things going wrong. Juniors design the happy path and patch failures as they appear. Seniors design the failure modes first, because that is where the cost lives.",
  topics: [
    {
      slug: "timeouts-retries",
      title: "Timeouts, retries and backoff",
      hook: "A call with no timeout is a hang with no end. A retry with no backoff is a self-inflicted outage.",
      minutes: 6,
      idea: [
        "Every call that leaves your process — HTTP, database, queue — can hang. Not fail: **hang**. A failure returns an error you can handle. A hang holds a connection, a thread and a user's patience indefinitely, and the default in most clients is to wait forever.",
        "",
        "So: **every external call gets a timeout**, and the timeout is a budget, not a guess. If your endpoint must answer in 2s and it makes three calls, those calls do not each get 2s.",
        "",
        "Once you have timeouts you need **retries**, because some failures are transient. Three rules:",
        "",
        "- **Only retry what is safe to retry.** That means idempotent operations. Retrying a non-idempotent write is how you get duplicates.",
        "- **Only retry what might succeed.** A 400 will be a 400 forever. Retrying it wastes your time and the other system's.",
        "- **Back off exponentially, with jitter.** Retry after 1s, 2s, 4s, 8s — plus a random offset. Without backoff, a struggling service gets hammered by every client at once and never recovers. Without jitter, all your clients retry in lockstep and arrive as a thundering herd.",
        "",
        "And the failure mode retries create: **a slow dependency becomes your outage**, because every one of your workers is sitting in a retry loop. The answer is a **circuit breaker** — after N consecutive failures, stop calling for a while and fail fast. Better to serve a clear error instantly than to time out slowly and take the whole service down with you.",
      ].join("\n"),
      bites: [
        "It bites as a cascade. One slow downstream service makes your request handlers pile up, which exhausts your connection pool, which makes every unrelated page on your site fail. The root cause is three services away and the symptom is everywhere.",
        "",
        "It bites in quieter ways too: an AI or payment call with no timeout that turns one user's request into a stuck function for fifteen minutes.",
      ].join("\n"),
      decisions: [
        "What is the timeout for this call, and how did I arrive at that number?",
        "Is this operation safe to retry? If not, fix that before adding retries.",
        "How many retries, and what backoff? Bounded, exponential, jittered.",
        "What do I do when I have exhausted retries — fail, degrade, or queue for later?",
        "Does this dependency need a circuit breaker, or is failing slowly acceptable here?",
      ],
      inYourCode: [
        "Find every `fetch` in your codebase and check which have a timeout. Most will not.",
        "Look at your AI assistant calls. Ask what a user sees if the provider takes 90 seconds.",
        "Pick one external dependency and write down what your app does when it is entirely down for an hour.",
      ],
      gotIt: [
        "Writing an external call, adding the timeout is part of writing it, not a follow-up ticket.",
        "You can explain why retrying without jitter is worse than not retrying.",
      ],
      deeper: [
        { label: "Release It! — Nygard, chapters 4–5 (stability antipatterns)" },
        {
          label: "AWS Builders' Library: Timeouts, retries and backoff with jitter",
          url: "https://aws.amazon.com/builders-library/timeouts-retries-and-backoff-with-jitter/",
        },
      ],
    },
    {
      slug: "partial-failure",
      title: "Partial failure and the two-write problem",
      hook: "The database write succeeded and the email did not. Now what?",
      minutes: 6,
      idea: [
        "Inside one database, a transaction makes two writes atomic. The moment a second system is involved — an email provider, a payment processor, a queue, a cache, a file store — **there is no transaction that covers both**. One will succeed and the other will fail, and you have to decide in advance what that leaves behind.",
        "",
        "The useful framing is: which inconsistency can you live with?",
        "",
        "- **Do the database write first, then the side effect.** If the side effect fails, you have a record and no email. Usually recoverable: you can retry from the record.",
        "- **Do the side effect first, then the write.** If the write fails, you have sent an email about something that does not exist. Usually not recoverable.",
        "",
        "So the default is: **commit the fact, then act on it.** Write the row, then let a retryable job send the email. This is the essence of the **outbox pattern** — record the intention in the same transaction as the data, and have something else deliver it, repeatedly if needed, until it succeeds.",
        "",
        "Which brings the other half: **at-least-once delivery**. Almost every queue, webhook and job runner guarantees at-least-once, never exactly-once. Exactly-once delivery is not available; exactly-once *effect* is, and you get it by making the consumer idempotent. This is why idempotency and partial failure are the same topic wearing two hats.",
        "",
        "Finally: **eventual consistency is a product decision, not a technical one.** \"The dashboard updates within a minute\" is fine if someone decided it and the UI says so. It is a bug if it happened by accident.",
      ].join("\n"),
      bites: [
        "It bites as reconciliation work that never ends: rows marked sent that were not sent, payments captured with no order, caches that disagree with the database and nobody can say which is right.",
        "",
        "It bites hardest in code that looks perfectly reasonable — three awaits in a row, each correct, with no transaction and no thought about what a crash between them leaves behind.",
      ].join("\n"),
      decisions: [
        "Which of these two systems is the source of truth?",
        "If the second step fails, is the state left behind recoverable or nonsense?",
        "Can I move the side effect out of the request and into a retryable job?",
        "Is the consumer idempotent? At-least-once delivery requires it.",
        "How long may these be inconsistent, and does the UI admit it?",
      ],
      inYourCode: [
        "Find a place that writes to Supabase and then calls something external. Ask what a crash in between leaves.",
        "Find a place that does the external call first. Ask whether that ordering was chosen or accidental.",
        "Pick one background job and ask what happens if it runs twice on the same row.",
      ],
      gotIt: [
        "You order the steps deliberately, and can say which inconsistency you chose.",
        "\"Exactly once\" sounds like a red flag rather than a feature.",
      ],
      deeper: [
        { label: "Designing Data-Intensive Applications — Kleppmann, chapters 8–9" },
        {
          label: "microservices.io: Transactional outbox",
          url: "https://microservices.io/patterns/data/transactional-outbox.html",
        },
      ],
    },
    {
      slug: "concurrency",
      title: "Races, lost updates and who wins",
      hook: "Two things happening at the same time is the default, not the exception.",
      minutes: 7,
      idea: [
        "A **race condition** is when the result depends on timing. They are hard because they are invisible in development — one user, one tab, one request at a time — and routine in production.",
        "",
        "The patterns worth recognising on sight:",
        "",
        "- **Lost update.** Two requests read a value, both add one, both write. One increment vanishes. Fix: do it in a single statement (`set n = n + 1`), or lock the row, or use a version column.",
        "- **Check-then-act.** You check a seat is free, then book it. Between the two, someone else booked it. Fix: make the check and the act one atomic operation — usually a unique constraint doing the checking for you.",
        "- **Double submit.** The same request arrives twice. Fix: idempotency, not a disabled button.",
        "- **Stale write.** A user loads a form, someone else edits, the first user saves and silently reverts them. Fix: **optimistic concurrency** — send the version you loaded, and reject the write if it has moved on.",
        "",
        "The two strategies underneath all of this:",
        "",
        "**Pessimistic locking** — take the lock, do the work, release it. Correct and simple; costs throughput, and two locks taken in different orders is a deadlock.",
        "",
        "**Optimistic concurrency** — assume no conflict, detect it at write time via a version or timestamp, retry or reject if it happened. Better under low contention, which is most things.",
        "",
        "And the framing worth internalising: **you cannot test your way to confidence here.** Races are found by reasoning about interleavings, not by running the suite again.",
      ].join("\n"),
      bites: [
        "It bites as bugs that will not reproduce. The report says a number is wrong, you cannot make it wrong, it is closed as unreproducible, and it happens again next month. That entire cycle is the signature of a race.",
        "",
        "It bites in optimistic UIs especially: the client applies a change locally, the server applies another, and the two never reconcile.",
      ].join("\n"),
      decisions: [
        "Can two of these run at once? For anything user-triggered or scheduled, assume yes.",
        "Is there a read-modify-write? Collapse it into one statement, or lock.",
        "Optimistic or pessimistic? Low contention favours optimistic.",
        "Who should win when two writers conflict — last write, first write, or an error the user sees?",
      ],
      inYourCode: [
        "Your todo store applies changes optimistically and resyncs on failure rather than rolling back. Read that code and work out which race it was written to avoid.",
        "Find a counter or total that is read, changed and written back.",
        "Take any action and imagine it firing twice, 50ms apart, from two tabs.",
      ],
      gotIt: [
        "You spot a check-then-act pattern while reading a diff.",
        "\"It doesn't reproduce\" makes you suspect a race rather than close the ticket.",
      ],
      deeper: [
        { label: "Designing Data-Intensive Applications — Kleppmann, chapter 7 (weak isolation)" },
        {
          label: "PostgreSQL docs: Explicit Locking",
          url: "https://www.postgresql.org/docs/current/explicit-locking.html",
        },
      ],
    },
    {
      slug: "caching",
      title: "Caching, and the invalidation problem",
      hook: "A cache is a deliberate decision to serve data that might be wrong. Make sure it was deliberate.",
      minutes: 6,
      idea: [
        "Caching trades correctness for speed. That trade is often worth it — but it is a trade, and the cost is paid later, by someone debugging why a user is seeing yesterday's number.",
        "",
        "Before caching anything, ask the question almost nobody asks: **why is this slow?** A cache in front of an unindexed query is a workaround that hides the real bug and doubles the surface area. Fix the query first.",
        "",
        "If you still want a cache, the four decisions:",
        "",
        "- **What is the key?** It must include everything that changes the result — including the user, or you will serve one user's data to another. This is a real and recurring class of security bug.",
        "- **How long does it live?** A short TTL is the simplest invalidation strategy and is usually enough. \"Stale for 60 seconds\" is a sentence a product owner can agree to.",
        "- **How is it invalidated?** TTL expiry, explicit invalidation on write, or tag-based. Explicit invalidation is the most correct and the most easily forgotten — every new write path must remember, forever.",
        "- **What happens on a miss?** If a popular key expires and a thousand requests all recompute it at once, you get a **stampede**. Mitigate with a lock, or by serving stale while revalidating.",
        "",
        "And the layer question. There are many caches between your database and a user's eye: the database's own buffers, your ORM, an in-process memo, Redis, the CDN, the browser. A stale value can live in any of them. **Know which layer you are caching at, and what it takes to clear it** — because during an incident, someone will ask.",
      ].join("\n"),
      bites: [
        "It bites as \"I changed it and nothing happened\", which sends people hunting through deploy logs for an hour. It bites worse as one user seeing another's cached page, which is a caching bug and a security incident at once.",
        "",
        "And it bites as permanent complexity: a cache is easy to add and almost impossible to remove, because by then everything depends on the speed it provides.",
      ].join("\n"),
      decisions: [
        "Is this slow because of a real cost, or a missing index? Fix the index first.",
        "Does the key include the user, the locale, the permissions — everything that changes the answer?",
        "TTL or explicit invalidation? TTL is weaker and far more reliable.",
        "Is stale-but-fast actually acceptable here, and does the UI say so?",
        "What is the blast radius if this cache serves wrong data for an hour?",
      ],
      inYourCode: [
        "List every caching layer between your Supabase rows and the browser, including Next.js's own. Name what clears each.",
        "Find a cached value whose key does not include the user id, and check whether it should.",
        "Find a comment in your codebase explaining why something deliberately does not revalidate. Your todo actions have one. Read it.",
      ],
      gotIt: [
        "\"Why is this slow?\" comes before \"let's cache it\".",
        "You can name every cache layer in your stack and how to clear each one.",
      ],
      deeper: [
        {
          label: "Next.js docs: Caching",
          url: "https://nextjs.org/docs/app/guides/caching",
        },
        { label: "Designing Data-Intensive Applications — Kleppmann, chapter 11" },
      ],
    },
  ],
};
