import type { Track } from "../types";

export const judgmentTrack: Track = {
  slug: "judgment",
  title: "Judgment",
  blurb:
    "This is the track that answers the actual question — what your lead is doing that you are not. It is not knowledge of a framework. It is a set of habits about how to approach a problem before touching it, how to size it, and how to own code regardless of who typed it.",
  topics: [
    {
      slug: "reading-code",
      title: "Building a mental model of a codebase",
      hook: "Senior engineers are not faster typists. They are faster readers, and they hold more of the system in their head.",
      minutes: 6,
      idea: [
        "Almost all of the speed difference you are seeing comes from here. Your lead is not solving the problem faster — she already knows where the problem lives, what else touches it, and what will break. That model was built by reading, deliberately, and it is buildable on purpose rather than by accumulation.",
        "",
        "**Trace one request end to end.** Pick a real user action and follow it: the component, the handler, the validation, the query, the tables, the response, the render. Write down every hop. Do this three times with three different features and you will know the codebase's spine. This single exercise is worth more than a month of incidental exposure.",
        "",
        "**Read the data model first, not the code.** The schema is the shortest honest description of what a system does. Code is how it currently does it; the schema is what it is.",
        "",
        "**Use history as documentation.** `git log` on a file, and `git blame` on a line that looks strange, will tell you *why* code exists. That is the question you actually have, and it is the one comments almost never answer. A weird-looking line is usually a bug fix with a story behind it. Find the commit and read the message.",
        "",
        "**Find the seams.** Every codebase has a few places where everything passes through — a middleware, a base client, a layout, a router. Learn those first; they explain the rest.",
        "",
        "**Change something small and watch what breaks.** Nothing builds a model faster than a deliberate experiment. Break it locally on purpose, see what fails, put it back.",
        "",
        "And the honest part: **write down what you do not understand.** A list of open questions is how you turn confusion into something you can resolve, instead of routing around it forever.",
      ].join("\n"),
      bites: [
        "Not having the model is what makes estimates wrong, changes risky and reviews shallow. You cannot judge whether a diff is right — yours or a model's — in a system you do not understand. Every other discipline on this list depends on this one.",
        "",
        "It bites specifically now, because AI removes the need to read code in order to change it. You can ship a working change to a file you have never opened, which is exactly how a year passes without a model forming.",
      ].join("\n"),
      decisions: [
        "Before changing this, do I know what else reads it?",
        "Is this line strange because it is wrong, or because it is a fix I do not know the story of?",
        "Do I understand this, or do I just have something that works?",
      ],
      inYourCode: [
        "Trace one full request through your own app end to end and write every hop on paper. Your invite-accept flow is a good one — it touches auth, tokens, RLS and two tables.",
        "Draw your app's architecture from memory, then check it. The gaps are your syllabus.",
        "Run `git blame` on the strangest line you can find in your codebase and read the commit message.",
      ],
      gotIt: [
        "Asked where a change would go, you can answer before opening the editor.",
        "You can predict what a change will break, and you are usually right.",
      ],
      deeper: [
        { label: "The Programmer's Brain — Felienne Hermans (how code reading actually works)" },
        { label: "Working Effectively with Legacy Code — Feathers, chapters 1–5" },
      ],
    },
    {
      slug: "scoping",
      title: "Breaking work down the way a lead does",
      hook: "Given the same ticket, the senior produces a different plan — usually smaller, sequenced, and with the risky part first.",
      minutes: 7,
      idea: [
        "Watch an experienced engineer take a task and you will see a specific, repeatable sequence before any code:",
        "",
        "**1. Restate the problem.** In one sentence, about the user, not the implementation. \"Reviewers can see private notes\" — not \"add a filter to the query\". Half of all bad work is a correct solution to a misread problem.",
        "",
        "**2. Find the real constraints.** What must not change. Who else depends on this. What the data already looks like. This is where generated code is weakest: it optimises the request in front of it and knows nothing about the constraint you did not mention.",
        "",
        "**3. Identify the risky unknown, and do it first.** Every task has one part that could invalidate the plan — an API that might not support what you need, a query that might be too slow, a migration that might not be safe. Juniors do the comfortable part first and hit the wall on Thursday. Seniors spike the risk on Monday, in thirty throwaway minutes, before committing to an approach.",
        "",
        "**4. Slice so every slice ships.** Not \"backend, then frontend, then tests\" — none of those is deliverable alone. Slice vertically: the narrowest thing that works end to end, then widen. A slice you can ship is a slice you can get feedback on, and one that cannot strand you mid-refactor.",
        "",
        "**5. Say what you are not doing.** Explicitly. Most scope creep is unspoken assumptions, not new requests.",
        "",
        "On estimates: your estimate is wrong because you estimate the happy path. The work is code plus edge cases plus review plus the thing you discover on day two. Estimate in **ranges tied to unknowns** — \"two days if the API supports filtering, four if I have to page through it\" — which is both honest and actually useful to the person planning around you.",
        "",
        "The strongest single habit here, and it is available to you today: **before starting, ask your lead how she would approach it.** Then compare with your own plan, and write down the difference. That difference, collected over a few months, is the gap made visible and closeable. Guessing at it from the outside takes years.",
      ].join("\n"),
      bites: [
        "It bites as the task that was two days and became two weeks, and as the branch that is nine days old with nothing shippable in it.",
        "",
        "It bites in code review as a 900-line diff nobody can review properly, which means it gets approved on trust and its bugs reach production.",
      ].join("\n"),
      decisions: [
        "What is the one-sentence problem, stated in terms of the user?",
        "What is the riskiest unknown, and can I spike it in an hour before committing?",
        "What is the smallest slice that works end to end and could ship on its own?",
        "What am I explicitly not doing?",
        "What is my estimate conditional on?",
      ],
      inYourCode: [
        "Take your next real task. Write your plan in five lines before asking anything, then ask your lead how she would do it, and log the delta.",
        "Look at your last large branch. Find the vertical slice that could have shipped on day one.",
        "Practise once: for a feature you want in this app, write down the risky unknown and spike it first.",
      ],
      gotIt: [
        "Your first instinct on a new task is to restate it and find the risk, not to open the editor.",
        "Your branches are small enough to review in one sitting, without effort.",
        "Your estimates come with the condition attached.",
      ],
      deeper: [
        { label: "Shape Up — Basecamp, on appetite and de-risking", url: "https://basecamp.com/shapeup" },
        { label: "The Pragmatic Programmer — tracer bullets and vertical slices" },
      ],
    },
    {
      slug: "reviewing-ai",
      title: "Owning code you did not write",
      hook: "The moment you accept a suggestion, you are the author. Every consequence is yours, and \"the model wrote it\" is not a defence anyone accepts.",
      minutes: 7,
      idea: [
        "Generated code has a specific and consistent failure profile. It is not random, which means you can review for it deliberately rather than reading nervously. What it reliably gets wrong:",
        "",
        "- **Plausible but wrong APIs.** Method names that should exist and do not, or exist with different semantics.",
        "- **Missing edge cases.** The happy path, cleanly. Empty, duplicate, concurrent, and dependency-down are usually absent.",
        "- **Ignored existing patterns.** A new helper beside the one you already have; a new naming convention; a second way of doing an existing thing.",
        "- **Weak data-layer decisions.** No transaction where two writes must both land, no index, wrong nullability, no constraint. It compiles, it passes, it is wrong in a way that lasts years.",
        "- **Swallowed errors.** Empty catches that turn a crash into silent corruption.",
        "- **Confidently wrong comments**, which is worse than none, because they tell the next reader something untrue.",
        "",
        "The structural risk is subtler and matters more to you specifically. **Reviewing is a weaker form of learning than writing.** You can accept correct code for a year and end up with a smaller model of the system than someone who wrote worse code by hand — because the understanding was never built. That is the actual mechanism behind the feeling you described, and it is worth naming plainly.",
        "",
        "Two habits fix it, and they cost very little:",
        "",
        "**Sketch your own approach first**, even three lines, before prompting. This is the only way you get a signal about whether your judgment is improving, because you find out whether you would have got there.",
        "",
        "**Make it explain, not just produce.** Ask why this approach over the alternative, what happens under concurrency, what it chose not to handle. Interrogating a design teaches you the design. Accepting a diff does not.",
        "",
        "And the line that settles most arguments with yourself: **if you cannot explain a line, you cannot merge it.** Not \"it works\" — explain it.",
      ].join("\n"),
      bites: [
        "It bites in review, where your lead asks why something is done that way and you find you do not know. That is a bad feeling, and it is also accurate information about what happened.",
        "",
        "It bites in production, where the missing transaction or absent index surfaces months later, long past the point where the original context is recoverable.",
      ].join("\n"),
      decisions: [
        "Did I sketch my own approach before asking? If not, I learn nothing from the comparison.",
        "Can I explain every line here, including the one that looks like boilerplate?",
        "Does this follow the patterns already in this codebase, or invent a second way?",
        "What edge cases did it skip — and did I check, or assume?",
        "What did it do at the data layer, and is that right for the next three years?",
      ],
      inYourCode: [
        "Take the last non-trivial thing you merged. Open the diff and try to explain every line out loud. Note each one you cannot.",
        "Find a generated function that touches two tables and check for a transaction.",
        "Pick one small task this week and do it with no AI at all. Where you struggle is the map of what to learn.",
      ],
      gotIt: [
        "You reject correct-looking code for not fitting the codebase.",
        "You can predict what a model will get wrong before reading the diff.",
        "Your own sketch is right more often than it was three months ago.",
      ],
      deeper: [
        { label: "Your own Rigor checklist — the diff stage is built from this list" },
      ],
    },
    {
      slug: "design-docs",
      title: "Thinking on paper before you build",
      hook: "A page of writing before a week of work is the highest-return hour in software, and almost nobody does it early enough.",
      minutes: 5,
      idea: [
        "Writing forces the precision that thinking lets you skip. You can hold a vague plan in your head indefinitely; you cannot write one down without noticing it is vague. That is the entire value, and it applies at one page just as well as at ten.",
        "",
        "A useful design doc is short and has roughly six parts:",
        "",
        "- **The problem.** Who has it, what it costs. No solution yet.",
        "- **Constraints.** What must not change, what the data already looks like, what is out of scope.",
        "- **The proposal.** What you will build, in enough detail to argue with. Include the data model — it is usually the load-bearing decision.",
        "- **Alternatives considered, and why not.** This is the section that makes a doc worth reading and the one most often skipped. It is also the section that protects you in six months when someone asks why you did not do the obvious thing.",
        "- **Risks and unknowns**, and what you will do about them.",
        "- **How it could fail**, in production, once it is live.",
        "",
        "For a normal task this is fifteen minutes and half a page. The threshold for writing one is low: if the work will take more than about two days, or touches data that already exists, or is hard to reverse, write it down first.",
        "",
        "The second-order benefit is the one that matters for you: **a doc is reviewable before it is expensive.** Your lead can correct your approach in ten minutes of reading, at a point where correcting it costs nothing. If she only sees the pull request, the approach is already built, you are attached to it, and the feedback arrives as rework.",
        "",
        "This is, practically speaking, the fastest available way to transfer someone's judgment to you. It moves the conversation to where the decisions actually are.",
      ].join("\n"),
      bites: [
        "Skipping it bites as a week of work redirected in review, and as decisions nobody can reconstruct later — including you, which turns every future change into archaeology.",
        "",
        "It bites as repeated arguments, because a decision that was never written down gets relitigated every few months.",
      ].join("\n"),
      decisions: [
        "Is this over two days, irreversible, or touching existing data? Then write the page first.",
        "What alternative am I not considering, and can I say why not?",
        "Who should read this before I build, and what do I want them to catch?",
        "How will this fail in production?",
      ],
      inYourCode: [
        "Write a one-page design for the next real feature you own, and give it to your lead before writing code. Watch which section she reacts to.",
        "Pick a decision already made in your codebase and write the alternatives section retroactively. It is good practice and surprisingly clarifying.",
        "Keep the docs. Re-reading your own from six months ago is the clearest measure of growth you will get.",
      ],
      gotIt: [
        "You reach for a page of writing when a task feels foggy, rather than starting and hoping.",
        "Your reviews are about the approach, before the code exists.",
      ],
      deeper: [
        {
          label: "Design Docs at Google — Malte Ubl",
          url: "https://www.industrialempathy.com/posts/design-docs-at-google/",
        },
        { label: "Writing as thinking — any Shape Up chapter on pitches" },
      ],
    },
  ],
};
