import type { Track } from "../types";

export const operatingTrack: Track = {
  slug: "operating",
  title: "Running it",
  blurb:
    "Writing the feature is half the job. The other half is being able to tell whether it works, find out why it does not, and change it later without a maintenance window. This is the half nobody teaches you and the half your lead does automatically.",
  topics: [
    {
      slug: "observability",
      title: "Seeing inside a system you cannot attach a debugger to",
      hook: "In production you cannot step through. You only know what you decided, in advance, to record.",
      minutes: 6,
      idea: [
        "Observability is the property of being able to answer new questions about a running system without shipping new code. It rests on three things, and they are not interchangeable:",
        "",
        "- **Logs** — discrete events with context. What happened, to whom, with what inputs.",
        "- **Metrics** — numbers aggregated over time. How many, how fast, how often failing.",
        "- **Traces** — one request's path across every service and call it touched, with timings.",
        "",
        "The single highest-leverage habit is **structured logging**. `console.log(\"failed\", err)` is unsearchable. `log.error({ event: \"invite_accept_failed\", inviteId, userId, reason })` can be filtered, counted and alerted on. The rule: **log objects, not sentences.**",
        "",
        "Then: **log decisions, not just errors.** The most useful line during an incident is rarely the exception — it is the one saying which branch was taken and why. \"Skipped XP award: day not tracked\" answers a support question in seconds.",
        "",
        "**Correlation ids** are what turn scattered lines into a story. One id, generated at the edge, attached to every log line for that request. Without it you have thousands of unrelated lines; with it you have one narrative.",
        "",
        "On metrics, the useful default is the **four golden signals**: latency, traffic, errors, saturation. And measure latency as **percentiles, never averages** — an average of 200ms hides the 2% of users waiting nine seconds, and those are the ones who leave.",
        "",
        "Finally, the discipline: **never log secrets, tokens or personal data.** Logs are copied, shipped to third parties and retained far longer than you expect.",
      ].join("\n"),
      bites: [
        "It bites during an incident, which is exactly when you have the least capacity to fix it. The bug is happening, you have no visibility, and your only option is to add logging and redeploy while the system is degraded.",
        "",
        "It bites quietly the rest of the time as questions nobody can answer: is this feature used? is it slower than last month? how often does this actually fail?",
      ].join("\n"),
      decisions: [
        "What question will I want answered at 2am, and does anything record the answer?",
        "Is this log line searchable — structured fields, or a sentence someone has to grep?",
        "Does this need a metric rather than a log? Anything you would count wants a metric.",
        "What is in this payload that must never be written down?",
      ],
      inYourCode: [
        "Pick your most important flow and try to reconstruct one user's journey through it from logs alone. Note every point where you cannot.",
        "Find a `catch` that logs nothing. That is a blind spot with a name.",
        "Add one structured log line at a decision point where you have previously had to guess.",
      ],
      gotIt: [
        "You add logging while writing the feature, aimed at a question, not after an incident.",
        "You ask for p95, not average.",
      ],
      deeper: [
        {
          label: "Google SRE Book — Monitoring Distributed Systems (the golden signals)",
          url: "https://sre.google/sre-book/monitoring-distributed-systems/",
        },
      ],
    },
    {
      slug: "debugging",
      title: "Debugging as a discipline, not guesswork",
      hook: "The gap is not that seniors know where bugs are. It is that they narrow the search systematically instead of guessing.",
      minutes: 6,
      idea: [
        "Most people debug by pattern-matching: this looks like a bug I have seen, try the fix, see if it helps. That works until it does not, and then it becomes hours of changing things at random. The alternative is a method, and it is genuinely learnable.",
        "",
        "**1. Reproduce it reliably first.** Until you can make it happen on demand, you cannot know you fixed it. Time spent getting a reliable repro is never wasted — it is the whole investigation in disguise. If it will not reproduce, that is itself evidence: think timing, state, data, environment.",
        "",
        "**2. Form a hypothesis you can be wrong about.** Not \"something is wrong with the invite code\" but \"the token is expired by the time the callback runs\". A hypothesis that cannot be falsified cannot guide you.",
        "",
        "**3. Bisect.** Halve the search space with every test. Is the bad value already wrong when it enters this function, or does it go wrong inside? That one question, asked repeatedly, finds anything. `git bisect` is the same idea applied to history, and it is startlingly effective on \"this used to work\".",
        "",
        "**4. Change one thing at a time.** Two changes and a fix means you do not know what fixed it, which means you have not fixed it.",
        "",
        "**5. Explain the whole path.** Not \"adding await fixed it\" but why the missing await produced that symptom. If the explanation has a gap, there is a second bug in the gap.",
        "",
        "And the rule that saves the most time: **read the error message. All of it.** Including the third line. People genuinely skip this, every day.",
      ].join("\n"),
      bites: [
        "It bites as time — hours that should have been minutes — and as fixes that are not fixes. A symptom suppressed without an understood cause comes back, usually in a worse form and further from the original code.",
        "",
        "It bites differently now that AI is in the loop: it is faster than ever to try twenty plausible fixes without understanding any of them. That feels like progress and is not.",
      ].join("\n"),
      decisions: [
        "Can I reproduce this on demand? If not, that is the first task.",
        "What is my actual hypothesis, stated so it could be proven wrong?",
        "What single test halves the search space?",
        "Do I understand the full causal chain, or only that the symptom stopped?",
      ],
      inYourCode: [
        "Take the next bug you hit and fix it with the debugger and logs only — no AI. Notice where you stall. That is your gap.",
        "Run `git bisect` once on something, just to have done it. It takes ten minutes to learn.",
        "Next time a fix works, write one sentence explaining why the bug produced that exact symptom. If you cannot, keep going.",
      ],
      gotIt: [
        "You reach for a repro before a fix.",
        "You can say why the bug caused the symptom, not just that the symptom is gone.",
      ],
      deeper: [
        { label: "Debugging — David J. Agans (nine rules, very short)" },
        { label: "Why Programs Fail — Zeller, chapters 1–5" },
      ],
    },
    {
      slug: "performance",
      title: "Where the time actually goes",
      hook: "Intuition about performance is wrong so reliably that acting on it without measuring is a habit worth breaking early.",
      minutes: 6,
      idea: [
        "The first discipline is **measure, then optimise**. Not because measuring is virtuous, but because the bottleneck is almost never where you think. Optimising the wrong thing costs you the time twice: once writing it, once maintaining the complexity forever.",
        "",
        "The numbers worth carrying in your head, because they set the scale of everything:",
        "",
        "- Memory access: ~100 nanoseconds",
        "- SSD read: ~100 microseconds — a thousand times slower",
        "- Network round trip in one datacentre: ~0.5 milliseconds",
        "- Network round trip across the world: ~150 milliseconds",
        "",
        "Which tells you the shape of nearly every web performance problem: **it is the round trips, not the computation.** Nobody's dashboard is slow because of a loop.",
        "",
        "Hence the single most common bug in this category, the **N+1 query**: fetch a list of 50 items, then fetch something for each one. Fifty-one round trips where two would do. It is invisible locally — 51 fast queries still feel instant — and fatal in production. Every ORM makes it easy and no ORM warns you.",
        "",
        "Then, in order of how often they matter for a web app: payload size, waterfalls (requests that could be parallel but are sequential), and only then actual computation.",
        "",
        "And a framing that stops most premature optimisation: **know the size of your data.** An O(n²) loop over 20 items is fine forever. A single extra query per row is not. The question is never \"is this fast\" but \"how does this grow\".",
      ].join("\n"),
      bites: [
        "It bites as a page that is fine for you and unusable for the user with three years of data. Your local database has forty rows; theirs has forty thousand.",
        "",
        "It bites as optimisation that made things worse: a cache added to hide an N+1, complexity added to save microseconds while a hundred milliseconds sat untouched next door.",
      ].join("\n"),
      decisions: [
        "Have I measured, or am I guessing?",
        "How many round trips does this page make, and how many are avoidable?",
        "How does this grow — with users, with rows, with time?",
        "Is this complexity buying a difference anyone can perceive?",
      ],
      inYourCode: [
        "Count the database queries on your dashboard for one page load. Then imagine a user with three years of sprints.",
        "Look for a `.map` containing an `await` on a query. That is an N+1.",
        "Find a page doing sequential awaits that could be one `Promise.all`. Your todo page already does this — see how.",
      ],
      gotIt: [
        "You spot an N+1 while reading code, not while profiling.",
        "You ask \"how does this grow?\" rather than \"is this fast?\".",
      ],
      deeper: [
        {
          label: "Latency numbers every programmer should know",
          url: "https://colin-scott.github.io/personal_website/research/interactive_latency.html",
        },
        { label: "Systems Performance — Gregg, chapter 2 (methodology)" },
      ],
    },
    {
      slug: "schema-change",
      title: "Changing a schema that already has data in it",
      hook: "A migration is a deploy that cannot be rolled back. Design it that way.",
      minutes: 6,
      idea: [
        "Creating a table is easy. Changing one that holds a year of production data, while the app is serving traffic, is a genuinely different skill — and it is one of the clearest places the experience gap shows.",
        "",
        "The core insight: **during a deploy, old code and new code run at the same time.** Not briefly in theory — actually, for minutes, across instances. So any migration that requires code and schema to change together will break something in that window.",
        "",
        "The answer is the **expand / migrate / contract** pattern, in three separate deploys:",
        "",
        "1. **Expand.** Add the new column, nullable, with a default. Old code ignores it; new code can use it. Nothing breaks.",
        "2. **Migrate.** Backfill the data in batches, and write to both old and new for a while. Deploy code that reads the new one.",
        "3. **Contract.** Once nothing reads the old column, drop it.",
        "",
        "Renaming a column in one step violates this and takes the site down. Renaming it as expand/migrate/contract is three boring deploys and zero downtime.",
        "",
        "The other operational traps, all of which are Postgres specifics worth knowing once:",
        "",
        "- **Adding a NOT NULL column with a default** rewrites the whole table on older versions, taking a lock for the duration. On a big table that is an outage.",
        "- **Adding an index** locks writes unless you use `CREATE INDEX CONCURRENTLY`.",
        "- **Long-running migrations hold locks**, and a lock queue blocks everything behind it, including reads.",
        "- **Backfills must be batched**, or one statement updates ten million rows in a single transaction.",
        "",
        "And the discipline: **every migration needs a plan for going backwards.** Not necessarily a down migration — often the honest answer is \"we cannot roll this back, so we deploy it on its own and watch\" — but a plan.",
      ].join("\n"),
      bites: [
        "It bites as the deploy that takes the site down and cannot be reversed, which is a uniquely unpleasant twenty minutes. Or as a backfill that locks the users table at 11am.",
        "",
        "It bites quietly as data loss: a column dropped that something still needed, and no backup granular enough to get just that back.",
      ].join("\n"),
      decisions: [
        "Will old and new code both run against this schema? They will. What breaks?",
        "Can this be expand/migrate/contract instead of one step?",
        "Does this statement take a lock, and for how long on production-sized data?",
        "Does the backfill need batching?",
        "If this goes wrong ten minutes in, what do I do?",
      ],
      inYourCode: [
        "Read your own numbered migrations in order. Find one that would have broken under a rolling deploy.",
        "Take a column you would like to rename and write out the three deploys it would actually take.",
        "Check whether your index creations use `CONCURRENTLY`. On a live table they need to.",
      ],
      gotIt: [
        "You think in deploys, not migrations — and know old code is still running.",
        "Renaming a column in one step looks dangerous rather than tidy.",
      ],
      deeper: [
        {
          label: "strong_migrations — a list of unsafe operations and their safe forms",
          url: "https://github.com/ankane/strong_migrations",
        },
        {
          label: "PostgreSQL docs: ALTER TABLE (read the locking notes)",
          url: "https://www.postgresql.org/docs/current/sql-altertable.html",
        },
      ],
    },
  ],
};
